### ISSUE TITLE
Parameter has no __pow__

### ISSUE THREAD

**Issue by grossardt** [Qiskit/qiskit#11226] opened 2023-11-10 00:20 UTC
### What should we add?

```
from qiskit.circuit import Parameter
a = Parameter('a')
a**2
```

will raise a `TypeError`: unsupported operand type(s) for ** or pow(): 'Parameter' and 'int' (tested with qiskit 0.44.1, qiskit-terra 0.25.1).
On the other hand, a**2 can be easily constructed as `(2 * a.log()).exp()` which yields `ParameterExpression(a**2)`

It seems reasonable to also implement `Paramater.__pow__` at least for int or float powers? Or is there a reason why this is not implemented that I am missing?

**Comment by kevinsung** [comment] 2023-11-10 00:21
Duplicate of https://github.com/Qiskit/qiskit/issues/8959

**Closed as completed by kevinsung** 2023-11-10 00:21 UTC
Labels: type: feature request

**Comment by grossardt** [comment] 2023-11-10 00:25
> Duplicate of #8959

Dang, missed that when searching. Thanks!
