### ISSUE TITLE
ModuleNotFoundError: No module named 'qiskit.util'

### ISSUE THREAD

**Issue by JoelDDA** [Qiskit/qiskit#11344] opened 2023-11-29 22:23 UTC
ModuleNotFoundError Traceback (most recent call last) Cell In[19], line 2

----> 2 from qiskit.optimization import QuadraticProgram

---> 88 from .problems.quadratic_program import QuadraticProgram

---> 54 from .quadratic_program import QuadraticProgram

---> 41 from qiskit.aqua import MissingOptionalLibraryError

---> 75 from .aqua_globals import aqua_globals

---> 19 from qiskit.util import local_hardware_info

ModuleNotFoundError: No module named 'qiskit.util'

**Comment by jakelishman** [comment] 2023-11-29 22:47
You must be running a very old version of Qiskit - `qiskit.aqua` has not existed for over two years now.  You should look into upgrading to a recent version of Qiskit (0.45 is the most recent), and the optimisation module has long since been a separate package: [`qiskit-optimization` on PyPI](https://pypi.org/project/qiskit-optimization/), which has [its documentation here](https://qiskit.org/ecosystem/optimization/).

If you have further problems with the optimisation module, I suggest you open them at https://github.com/qiskit-community/qiskit-optimization, which is where that module lives now - it's not a part of core Qiskit.

**Comment by JoelDDA** [comment] 2023-11-29 23:15
[image: image.png]

**Comment by JoelDDA** [comment] 2023-11-30 01:54
can you help me with the code, please?

**Comment by 1ucian0** [comment] 2023-12-06 12:31
As @jakelishman mentioned, there is big chances that you are running packages that are unmaintained or reached end-of-life support, so I'm closing this issue. If you still thing that there is a bug in the current supported version of Qiskit, please leave a comment or open a new issue with instructions on how to reproduce the problem and the version of Qiskit and Python you are running.

**Closed as not planned by 1ucian0** 2023-12-06 12:31 UTC
