### ISSUE TITLE
Pauli Twirling not improving results

### ISSUE THREAD

**Issue by d-bharadwaj** [Qiskit/qiskit#13542] opened 2024-12-09 16:34 UTC
### Environment

- **Qiskit version**:  1.2.4
- **Python version**: 3.10.15
- **Operating system**:  Linux - Ubuntu

### What is happening?

I see no consistent improvement in implementing Pauli Twirling with EstimatorV2. I've attached a toy example below. Sometimes the Pauli Twirling results are better and other times they are not. I am unsure why the results are inconsistent. 

### How can we reproduce the issue?

```import qiskit
import numpy as np
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit.quantum_info import SparsePauliOp
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
import qiskit.quantum_info as qi
from qiskit_ibm_runtime.fake_provider import FakeMumbaiV2
# Import from Qiskit Aer noise module
from qiskit_aer import AerSimulator
from qiskit_aer.noise import (NoiseModel, coherent_unitary_error)

def test_circuit(n):
    qc = qiskit.QuantumCircuit(n)
    qc.h(0)
    for i in range(n - 1):
        qc.cx(i, i + 1)
        if i + 2 < n:
            qc.cz(i + 1, i + 2)
    return qc

num_qubits = 5
np.random.seed(0)
paulis = ["".join(np.random.choice(['I', 'X', 'Y', 'Z'], size=num_qubits)) for _ in range(num_qubits+1)]
qc = test_circuit(num_qubits)

np.random.seed(0)
coeffs = np.random.random(len(paulis))
observable = SparsePauliOp.from_list(list(zip(paulis, coeffs)))

#Aer Backend
backend = AerSimulator(method='statevector', device='GPU',seed_simulator = 0)


#Ideal Simulation 
ideal_estimator = Estimator(mode=backend)
ideal_estimator.options.seed_estimator=0
pm = generate_preset_pass_manager(backend=backend, optimization_level=1,seed_transpiler=0)
isa_circuit = pm.run(qc)
isa_observable = observable.apply_layout(isa_circuit.layout)
job = ideal_estimator.run([(isa_circuit, isa_observable)])
# Get results for the first (and only) PUB
ideal_res = job.result()[0].data.evs

#Noisy Simulation
noise_model = NoiseModel()
##Coherent Noise
epsilon = 0.1
err_cx = qiskit.QuantumCircuit(2)
err_cx.cx(0,1)
err_cx.p(epsilon, 0)
err_cx.p(epsilon, 1)
err_cx.cx(0,1)
err_cx.p(-epsilon, 0)
err_cx.p(-epsilon, 1)
err_cx = qi.Operator(err_cx)
noise_model.add_all_qubit_quantum_error(
    coherent_unitary_error(err_cx), ["cx"])

noisy_backend =  FakeMumbaiV2()
noisy_estimator = Estimator(mode=noisy_backend)
(noisy_estimator.options.simulator.noise_model) = noise_model

pm = generate_preset_pass_manager(backend=noisy_backend, optimization_level=1)
isa_circuit = pm.run(qc)
isa_observable = observable.apply_layout(isa_circuit.layout)
job = noisy_estimator.run([(isa_circuit, isa_observable)])
noisy_res = job.result()[0].data.evs

## PT Mitigation
pt_estimator = Estimator(mode=noisy_backend)
pt_estimator.options.twirling.enable_gates = True
pt_estimator.options.twirling.num_randomizations = 100
pt_estimator.options.twirling.shots_per_randomization = 1000
pt_estimator.options.simulator.noise_model = noise_model

pm = generate_preset_pass_manager(backend=noisy_backend, optimization_level=1)
isa_circuit  = pm.run(qc)
isa_observable = observable.apply_layout(isa_circuit.layout)
job = pt_estimator.run([(isa_circuit, isa_observable)])
pt_res = job.result()[0].data.evs

improvement_factor = (abs(noisy_res - ideal_res)) / (abs(pt_res - ideal_res))
print(f"Factor of improvement: {improvement_factor}")```

### What should happen?

Firstly, we should see improvement with Pauli Twirling since there is a coherent noise model attached to the backend. The results should also be consistent, but I see very different factors of improvement each time I run the simulation.

### Any suggestions?

Although [this](https://docs.quantum.ibm.com/guides/error-mitigation-and-suppression-techniques) qiskit page contains information on enabling Pauli Twirling with EstimatorV2, there is no tutorial showing how actually to implement it. You can also share information if we can do Pauli Twirling with SamplerV2.

**Comment by joeharrisuk** [comment] 2024-12-10 10:01
When you're in [local testing mode](https://docs.quantum.ibm.com/guides/local-testing-mode), all estimator options except shots are ignored, so presumably there's no twirling taking place. When I run your code (I'm on qiskit version 1.3.0, qiskit_ibm_runtime version 0.34.0), I get a `UserWarning` telling me that these options are being ignored.

**Comment by joeharrisuk** [comment] 2024-12-10 10:03
By the way, if you want to perform Pauli twirling locally, you could do it by writing your own transpiler pass. There's a good tutorial here which specifically considers Pauli twirling: https://docs.quantum.ibm.com/guides/custom-transpiler-pass

**Comment by Cryoris** [comment] 2024-12-10 12:17
Pauli twirling in itself is not necessarily guaranteeing to reduce errors; it is a technique to convert noise channels into stochastic Pauli errors by suppressing coherent error contributions. This effect can be seen e.g. in terms of the Pauli transfer matrix of an identity operation, where it suppresses off-diagonal terms. Twirling is mainly used in composition with other error mitigation techniques, that rely on the noise channel being stochastic. 

In any case, this is not a bug within the Qiskit SDK, which deals with circuits and transpilation. Questions of this scope would be better suited for the Qiskit slack channel or maybe you can have a look at more advanced options e.g. on https://docs.quantum.ibm.com/guides/configure-error-mitigation. I'll go ahead and close this issue, but if there's a problem with the construction of compilation of the circuits, feel free to re-open it and we can discuss.

**Closed as not planned by Cryoris** 2024-12-10 12:17 UTC
Labels: bug
