### ISSUE TITLE
Bind_parameters fails to detect values are real

### ISSUE THREAD

**Issue by Arvendui** [Qiskit/qiskit#9663] opened 2023-02-25 13:55 UTC
### Environment

- **Qiskit Terra version**: 0.23.2
- **Python version**: 3.8
- **Operating system**: macOS 12.6

### What is happening?

I am having issues with the procedure of binding values for some parameters. From the error messages etc is seems that the passes value is not real, but I am sure that they are. Furthermore, by saving the circuit with qpy, and opening in in another file and there binding it to the same values yields no error.

### How can we reproduce the issue?

The code can be found at this repo: [https://github.com/Arvendui/qiskit_bind_params](https://github.com/Arvendui/qiskit_bind_params)
The file ``mwe.py`` reproduces the error and saves the circuit. The circuit can be opened and the values binded in ``for_issue.py``, without any errors.
The other files are needed for imports.

### What should happen?

The file ``mwe.py`` generates the error that is troublesome, as the fact that saving the circuit and running it in ``for_issue.py`` runs without errors.

**Comment by Cryoris** [comment] 2023-04-07 12:01
Hi @Arvendui, thanks for the report. Could you reduce the `mwe.py` to a smaller example? Ideally, a minimal example has only the bare minimum of Qiskit logic to reproduce the bug, but in the snippet you reference there is a lot happening 🙂 Also, the circuit used in `for_issue.py` doesn't seem to be in the repository.

Without running the script, it seems the parameters you are trying to bind
```python
    local_mapped_circ.bind_parameters([0.1, 0.1])
```
are real, so likely the underlying circuit has some complex coefficients that makes this fail.

**Comment by Arvendui** [comment] 2023-04-10 15:18
Hi @Cryoris, thanks for the feedback. I will try to reduce more the mwe, but the code was already reduced by much. The main problem is that I don't understand where the error is coming from. I think that before you spend a crazy amount of time into it, the best is if you could elaborate a bit more on "so likely the underlying circuit has some complex coefficients that makes this fail.": do you mean that I am passing some complex numbers somewhere else? Would that be happening when using ``bind_parameters``? 

The circuit to be ran in ``for_issue.py`` is generated by first running ``mwe.py`` (which produced the error, and on the other hand opening that again in ``for_issue.py``does not produce the error).

**Comment by Cryoris** [comment] 2023-04-12 07:12
I mean that there might be a calculation that was done with complex numbers and there might be a small complex residual. For example in the following, `sin(10 pi)` should be 0, but isn't due to numerical roundoff, which causes the complex parameter error.
```python
import numpy as np
from qiskit.circuit import QuantumCircuit, Parameter

x = Parameter("x")
qc = QuantumCircuit(1)
qc.rx(np.cos(x) + 1j * np.sin(x), 0)

print(np.cos(10 * np.pi) + 1j * np.sin(10 * np.pi))
qc.bind_parameters([10 * np.pi])  # error: complex parameter
```

One thing you could try is to print the value of the parameter in `validate_paramters` in the `Gate` class on L228, to investigate what numerical value your parameters have and why they are recognized as complex.

**Comment by jakelishman** [comment] 2023-12-19 15:30
Closing this as "cannot reproduce" due to the lack of minimisation in the example.  If you're able to reduce your example (to a reasonable single code block - 1000 lines of unrelated code is not minimal - see [the instructions on what constitutes a MWE](https://stackoverflow.com/help/minimal-reproducible-example)), and it's still showing similar problems, please feel free to re-open.

**Closed by jakelishman** 2023-12-19 15:30 UTC
Labels: bug
