### ISSUE TITLE
Different results between original and transpiled circuits

### ISSUE THREAD

**Issue by Matt-Stypulkoski** [Qiskit/qiskit#3689] opened 2020-01-06 16:43 UTC
### Information

- **Qiskit Terra version**:  0.11.0
- **Python version**: 3.7.5
- **Operating system**: MacOS Mojave 10.14.6

### What is the current behavior?
Pulled from this stack exchange question: https://quantumcomputing.stackexchange.com/questions/9375/cannot-replicate-results-in-article-on-pricing-financial-derivatives-on-ibm-q

The original circuit is built in this way:
```
qc = QuantumCircuit(4, 4)
qc.h([0, 1, 2])
qc.ry(1.00, 3)
qc.rz(0.33, 3)
qc.cu3(1.6, -1.12, 2.03, 2, 3)
qc.cu3(2.23,0.51,3.65, 1, 3)
qc.cu3(0.8,-4.53,-1.39, 0, 3)
qc.h(0)
qc.cu1(np.pi/-2, 0, 1)
qc.cu1(np.pi/-4, 0, 2)
qc.h(1)
qc.cu1(-np.pi/2, 1, 2)
qc.h(2)
qc.measure(range(4), range(4))
```
drawn as such:
<img width="864" alt="Screen Shot 2020-01-06 at 11 09 12 AM" src="https://user-images.githubusercontent.com/50181769/71830577-04ea6b00-3075-11ea-9a0c-9b03b6fb2c4c.png">

After executing the following code, I see that the circuit is transpiled and returns different results.
```
sim = prov.get_backend('ibmq_qasm_simulator')
job = execute(qc, sim)
```
Transpiled circuit:
![circuit](https://user-images.githubusercontent.com/50181769/71831760-91962880-3077-11ea-8585-12cb761a6f39.png)

The issue I have found is the same as the one the user asking the original stack exchange question had. The original circuit should return results similar to around 60%: `0111` and around 30%: `1111`, based on the paper in the stack exchange and the measurement probabilities shown on IQX. However, after executing the circuit, we get results similar to around 55%: `0000` and 30%: `1000`

### Steps to reproduce the problem
Execute the original circuit above on the simulator.

### What is the expected behavior?
Expected results should be similar to to the returned results.

**Comment by mtreinish** [comment] 2020-01-06 17:05
How were you running the original circuit without transpiling it? The gates need to be unrolled to the basis set at least to run on aer (I'm testing it locally not using the online version but they should be the same). Running the input circuit with optimization level 0 (which will just unroll no other optimizations) 

![level_0](https://user-images.githubusercontent.com/2447371/71834187-9b6e5a80-307c-11ea-8b4c-a058954d3eaa.png)

and with optimization level 1 (the default for `execute()`) returned similar results.

```
Level 0:
{'0000': 558, '0100': 29, '1010': 12, '0110': 16, '1101': 16, '0001': 2, '0101': 2, '1001': 37, '1110': 5, '1100': 15, '0111': 4, '1111': 26, '0010': 8, '1000': 294}
Level 1:
{'0000': 559, '0100': 27, '1010': 20, '0110': 14, '1101': 18, '0001': 7, '0101': 4, '1001': 32, '1110': 7, '1100': 10, '0111': 5, '1111': 19, '0010': 17, '1000': 285}
```

**Comment by Matt-Stypulkoski** [comment] 2020-01-06 17:15
I ran the circuit by using `execute()`, so it would've transpiled the circuit at `optimiation_level=1` if I understood it correctly. The measurement probability I was seeing for the original circuit before transpilation was what I saw through the IBM Q Experience Circuit Composer: 
<img width="1611" alt="Screen Shot 2020-01-03 at 2 40 43 PM" src="https://user-images.githubusercontent.com/50181769/71834691-cefdb480-307d-11ea-9608-18714c0e18f3.png">
 
This probability also matched the probability found in the paper that the stack exchange poster had mentioned.

The results you posted match the results I received when I ran the circuit with `execute()` on the `ibmq_qasm_simulator`, but these results are different than the expected results I saw in IBM Q Experience and in the original stack exchange question.

**Comment by ajavadia** [comment] 2020-01-07 05:34
I think all of those gates are in the Aer simulator basis so no unrolling will be done.

I'm guessing a phase issue with CU3, @chriseclectic can you check the definition of CU3 in terra and aer match? (related to https://github.com/Qiskit/qiskit-terra/pull/2755/files)

**Comment by mtreinish** [comment] 2020-01-07 14:02
> I think all of those gates are in the Aer simulator basis so no unrolling will be done.
> 

In my local testing it needed to unroll Ry and Rz. With those in the circuit passed to Aer it raised an internal error caused by https://github.com/Qiskit/qiskit-aer/blob/master/src/simulators/densitymatrix/densitymatrix_state.hpp#L570-L573 (they're also not listed in the basis set: https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/backends/qasm_simulator.py#L212-L217).

But, I was more asking to understand where/how the circuit was being run with the expected result, because without transpilation the results were the same locally. But, since the circuit composer doesn't use aer that makes sense.

**Comment by jakelishman** [comment] 2023-12-21 01:47
After the discussion here, it seems that [the answers on that StackOverflow post concluded that the circuit is not correct for the desired results / algorithm](https://quantumcomputing.stackexchange.com/a/9525).  Closing now, but feel free to open a new issue if there's more to discuss.

**Closed by jakelishman** 2023-12-21 01:47 UTC
Labels: bug
