### ISSUE TITLE
Issue in Creating Controlled Custom Gate if Circuit Containing IGate 

### ISSUE THREAD

**Issue by XinboUM** [Qiskit/qiskit#11033] opened 2023-10-18 02:26 UTC
### Environment

- **Qiskit Terra version**: 0.25.1
- **Python version**: 3.11.4
- **Operating system**: macOS Ventura version 13.5.1

### What is happening?

When calling the `to_gate().control()` method on a `QuantumCircuit`, if the `QuantumCircuit` contains an `IGate`, an error `qiskit.exceptions.QiskitError: "Error decomposing node of instruction 'id': 'NoneType' object has no attribute 'global_phase'. Unable to define instruction 'id' in the given basis."` is thrown. While this may seems as a contrived example (because one can avoid this error message by removing `IGate` in the circuit), this indicates that the implementation of `IGate` can be improved.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.circuit.library import YGate, IGate

circ = QuantumCircuit(2)
circ.append(YGate(), [0])

gate = circ.to_gate()
gate.control(1)

circ.append(IGate(), [1])

gate = circ.to_gate()
gate.control(1) # ERROR
```

### What should happen?

No error message should occur when a circuit containing `IGate` is used for making a controlled version of a customized gate.

**Comment by jakelishman** [comment] 2023-10-20 14:00
Thanks for the report.  This is a duplicate of #4010, and it's fixed on `main` by a combination of #10607 and #7146, so I'll close this now - the fix will be released in Qiskit 0.45 in about two weeks' time.

**Closed as completed by jakelishman** 2023-10-20 14:00 UTC
Labels: bug
