### ISSUE TITLE
Transpiler with target unrolls even if gate is natively supported

### ISSUE THREAD

**Issue by burgholzer** [Qiskit/qiskit#10592] opened 2023-08-08 18:18 UTC
### Environment

- **Qiskit Terra version**: 0.25.0
- **Python version**: 3.11
- **Operating system**: Ubuntu 22.04

### What is happening?

Calling `transpile` with a custom target on a circuit causes transpilation even though all gates of a circuit are in the target's list of supported operations. See the below MRE that demonstrates the issue.
The underlying issue is much broader than that. Given a target that contains the `U3Gate` and _any_ other single-qubit gate, the transpiled circuit will always contain a `u3` gate instead of the original gate.

### How can we reproduce the issue?

```python3
import qiskit.circuit.library as qcl
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import Parameter
from qiskit.transpiler import Target

target = Target(num_qubits=1)
target.add_instruction(qcl.XGate())
target.add_instruction(qcl.U3Gate(Parameter("theta"), Parameter("phi"), Parameter("lam")))

qc = QuantumCircuit(1)
qc.x(0)
qc_transpiled = transpile(qc, target=target)
print(qc_transpiled.data[0][0])
```
yields
```console
u3
```

### What should happen?

The `X` gate is in the list of supported instructions. As such, I would have expected no transpilation to take place and that `qc == qc_transpiled`.

Interestingly, using 
```python3
qc_transpiled = transpile(qc, basis_gates=["x", "u3"])
```
produces the desired result.

### Any suggestions?

If the behavior above is not desired, it is at least unexpected and some clarification would be great.
If this is really a bug, I suspect that some early stopping criterion is missing somewhere.

**Comment by mtreinish** [comment] 2023-08-22 17:55
I came across the same thing too, I had opened: https://github.com/Qiskit/qiskit/issues/10568 to track it. I'm going to close this as a duplicate of it. The specific issue is basically this function: https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py#L152-L180 isn't taking into account that the default should be to not translate the gate if the all have the same error rates (which in a simulator will be None).

**Closed by mtreinish** 2023-08-22 17:55 UTC
Labels: bug

**Comment by burgholzer** [comment] 2023-08-22 18:02
> I came across the same thing too, I had opened: #10568 to track it. I'm going to close this as a duplicate of it. The specific issue is basically this function: https://github.com/Qiskit/qiskit/blob/main/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py#L152-L180 isn't taking into account that the default should be to not translate the gate if the all have the same error rates (which in a simulator will be None).

Ah thanks for bringing that up and sorry for the noise. Is that something you have on the radar internally and are working on a fix or would you appreciate a community contribution there?

**Comment by mtreinish** [comment] 2023-08-22 18:06
I haven't started to work on it besides identifying the root cause a few weeks ago. If you have the bandwidth to work on it that would be greatly appreciated. If you leave a comment on #10568 I can assign the issue to you.
