### ISSUE TITLE
Qiskit visualization ignores control qubit as idle_wires when following a barrier. 

### ISSUE THREAD

**Issue by smajumderibm** [Qiskit/qiskit#13171] opened 2024-09-17 19:58 UTC
### Environment

- **Qiskit version: 1.1.0 **: 
- **Python version: 3.12.5**: 
- **Operating system: MAC**: 

### What is happening?

circuit.draw() is incorrectly drawing circuit with barriers in them. 
<img width="344" alt="Screenshot 2024-09-17 at 3 54 11 PM" src="https://github.com/user-attachments/assets/add8c614-0082-4b72-88cf-09466b5a8332">

### How can we reproduce the issue?

# Returns the right visualization
qc =  QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.draw(fold=-1, output='mpl', idle_wires=False)

# Returns a wrong visualization
qc =  QuantumCircuit(2)
qc.h(0)
qc.barrier()
qc.cx(0, 1)
qc.draw(fold=-1, output='mpl', idle_wires=False)

### What should happen?

The expected behavior is to include both qubits in the circuit and show the CX gate.

**Comment by jakelishman** [comment] 2024-09-17 20:34
Are you sure this was with Qiskit 1.1.0?  I can't reproduce a bug like that, but there is a known bug in Qiskit 1.2.0 and 1.2.1 that most likely has this effect (see #13128 and #13146, which are fixed by #13149).

**Comment by smajumderibm** [comment] 2024-09-17 20:40
My bad, it is in Qiskiit 1.2.1.

**Comment by jakelishman** [comment] 2024-09-17 20:49
No worries - in that case this is a duplicated of #13146, and it's just in the process of being fixed by #13149, which will be released in Qiskit 1.2.2, probably later this week.  I'll close this as a duplicate for now, but feel free to open more issues if there are more problems.

**Closed as completed by jakelishman** 2024-09-17 20:49 UTC
Labels: bug
