### ISSUE TITLE
Malfuctioning of the if_test in distributed controlled phase shift.

### ISSUE THREAD

**Issue by jorgevazquezperez** [Qiskit/qiskit#9405] opened 2023-01-20 12:59 UTC
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.9.0
- **Operating system**: Ubuntu 20.04 LTS

### What is happening?

I was developing the distributed version of the QPE. For that I needed to use the cat entangler and cat disentangler circuits, which are the following:

![image](https://user-images.githubusercontent.com/45230006/213692259-0505dc71-65af-411e-ba88-aaa9bc1f302a.png)

The first square corresponds to the cat entangler and the second to the cat disentangler, the effect of this circuits is explained in [1]. That CNOT in the middle of the squares is replaced by the controlled phase shift, the first qubit is preparated for the phase shift using a Hadamard gate and the last qubit is prepared to $|1\rangle$. The resulting circuit is as follows:

![image](https://user-images.githubusercontent.com/45230006/213695643-faf7e9c8-ef1c-49b7-b2e4-080dec79e825.png)

In theory, the state of the hole circuit at the barrier should be:

$$
|\psi\rangle = \frac{1}{\sqrt(2)}[|0\rangle + e^{\frac{i\pi}{2}}|1\rangle]|001\rangle
$$

And so, after reverting the phase gate and applying the Hadamard gate before the measurement, the result of the measure should be sharp, meaning that we should get $0$ in every shot. But, instead of this, the result is one half of the counts goes to $0$ and half to $1$, meaning that the qubit is some point of the ecuador of the Bloch sphere (it is important to say that the qubit is not neither on $|+\rangle$ state nor on $|-\rangle$ state). So, the `if_test` has some effect on the first qubit but not the expected.

On the other hand, if we implement the circuit with the `c_if` directive we obtain the desired results.

Works Cited
[1] Yimsiriwattana, Anocha, and Samuel J. Lomonaco. Generalized GHZ States and Distributed Quantum Computing. arXiv, 2004, https://doi.org10.48550/ARXIV.QUANT-PH/0402148.

### How can we reproduce the issue?

The cat entangler and the cat disentangler can be programmed as follows:

CAT ENTANGLER
```
circuit = QuantumCircuit(*self.qregs, name=self.name)
circuit.add_register(ClassicalRegister(1))

self._create_cat_state(circuit)
circuit.cx(0, 1)
circuit.measure(1, 0)

with circuit.if_test((circuit.clbits[0], 1)):
    for i_qubit in range(1,num_qubits):
        circuit.x(i_qubit)
```

CAT DISENTANGLER
```
circuit = QuantumCircuit(qregs, name="Cat Entangler")
circuit.add_register(ClassicalRegister(num_qubits-2))

for i_qubit in range(2,num_qubits):
    circuit.h(i_qubit)
for i_qubit, j_clbit in zip(range(2, num_qubits), range(num_qubits-2)):
    circuit.measure(i_qubit, j_clbit)
    with circuit.if_test((circuit.clbits[j_clbit], 1)) as else_:
        circuit.x(i_qubit)
    with circuit.if_test((circuit.clbits[j_clbit], 1)) as else_:
        circuit.z(0)
```

Note that this implementation works if we try to make a distributed CNOT gate. Just doesn't work if we want a distributed phase shift.

### What should happen?

As we said, the result of the measure should be sharp, meaning that we should get $0$ in every shot. That is what it should happen and what happens if we use `c_if`.

**Comment by jakelishman** [comment] 2023-01-20 13:03
Please can you provide a full reproducer, including whatever you were using to generate the counts?  It would also help if you could provide the working version of the code.

**Comment by jorgevazquezperez** [comment] 2023-01-30 09:26
Yes, of course! I am not really experimented on reporting issues, so thank you for the point out. First of all, the main file has the following appearence:

```
import math

# Import the cat entangler and disentangler
from cat_disentangler import CatDisentangler
from cat_entangler import CatEntangler

# importing Qiskit utilities
from qiskit import IBMQ, Aer, transpile, assemble
from qiskit.execute_function import execute
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.circuit.library import QFT
from qiskit.circuit.library import PhaseGate

phase_input = 1/3
n_eval = 3

# Here we use this variable to make the QPE distributed or not
distributed = True

iqft = QFT(n_eval, inverse=True, do_swaps=False)

if distributed:
    qr_eval = QuantumRegister(n_eval, "eval")
    qr_aux = QuantumRegister(2*n_eval, "aux")
    qr_state = QuantumRegister(1, "q")
    cl_eval = ClassicalRegister(n_eval, "cl_eval")
    cl_aux = ClassicalRegister(2*n_eval, "cl_aux")

    qr_list = [qr_eval, qr_aux, qr_state]
    cl_list = [cl_eval, cl_aux]
    qpe = QuantumCircuit(*qr_list, *cl_list, name="QPE")

    qpe.x(qr_state[0])
    qpe.h(qr_eval)  # hadamards on evaluation qubits

    for j in range(n_eval):
        qubits_list = [qr_eval[j], qr_aux[2*j], qr_aux[2*j + 1]]
        qpe.compose(CatEntangler(3), qubits=qubits_list, clbits=[cl_aux[2*j]], inplace=True)
        qpe.append(PhaseGate(theta = 2*math.pi*phase_input).power(2**(n_eval-j-1)).control(), qargs=[qr_aux[2*j + 1]] + qr_state[:])
        qpe.compose(CatDisentangler(3), qubits=qubits_list, clbits=[cl_aux[2*j+1]], inplace=True)
        
else:
    qr_eval = QuantumRegister(n_eval, "eval")
    qr_state = QuantumRegister(1, "q")
    cl_eval = ClassicalRegister(n_eval, "cl_eval")

    qr_list = [qr_eval, qr_state]
    qpe = QuantumCircuit(*qr_list, cl_eval, name="QPE")

    qpe.x(qr_state[0])
    qpe.h(qr_eval)  # hadamards on evaluation qubits

    for j in range(n_eval):  # controlled powers
        qpe.append(PhaseGate(theta = 2*math.pi*phase_input).power(2**(n_eval-j-1)).control(), qargs=[j] + qr_state[:])

qpe.append(iqft, qargs=qr_eval)

# Measure and print the circuit
qpe.barrier()
for n in range(n_eval):
    qpe.measure(qr_eval[n],cl_eval[n])
print(qpe)

aer_sim = Aer.get_backend('aer_simulator')
t_qpe = transpile(qpe, aer_sim)
intermediate = aer_sim.run(t_qpe)
results = intermediate.result()
answer = results.get_counts()

# We process the answer to get only the results of measuring the eval qubits
def process_answer(answer):
    new_dict = {}
    for key, count in answer.items():
        keys = key.split()
        if len(keys) < 2:
            return
        new_key = keys[1]
        if new_key in new_dict:
            new_dict[new_key] = new_dict[new_key] + count
        else:
            new_dict[new_key] = count
    return new_dict

results = process_answer(answer)
if results is None:
    print(answer)
else:
    print(results)
```

Then, the cat entangler and cat disentangler used are in the following zip file:

[cat.zip](https://github.com/Qiskit/qiskit-terra/files/10534261/cat.zip)

Note that the files ending in `if_test` are the ones using the `if_test` for the intermediate measures and the other ones are the ones using `c_if`. If there is something more needed tell me!

**Comment by jakelishman** [comment] 2023-02-16 14:05
Sorry it took me a while to respond here.  Thanks for the extra code - it's helpful.  There's a lot going on here, though, and I'm not 100% sure that `if_test` is actually the problem.  I tried to run your reproducer with the current main branch of `qiskit-terra`, and it's telling me that there's some calls to `QuantumCircuit.compose` where the interior circuit doesn't have the number of clbits that are expected:
```text
jake@ninetales$ python repro.py
Traceback (most recent call last):
  File "/Users/jake/tmp/pr9405/repro.py", line 38, in <module>
    qpe.compose(CatEntangler(3), qubits=qubits_list, clbits=[cl_aux[2*j]], inplace=True)
  File "/Users/jake/code/qiskit/terra/qiskit/circuit/quantumcircuit.py", line 918, in compose
    raise CircuitError(
qiskit.circuit.exceptions.CircuitError: 'Number of items in clbits parameter (1) does not match number of clbits in the circuit (0).'
```
where `repro.py` is a file copy-pasted from your code block.

In Terra 0.22.2 (which is what you mentioned you've got), we didn't have that error-checking in place, so `QuantumCircuit.compose` could sometimes produce invalid circuits, instead of correctly throwing exceptions.  I think if you upgrade to Terra 0.23, it should help find the problems. Looking quickly to me, it looks like your `CatEntangler` doesn't create its inner circuit object with any `clbits` at all, so most like the problems you're seeing are related to that - Terra 0.22 was letting you build a circuit object that was internally inconsistent.

Could you try upgrading to Terra 0.23, fixing the places where there's the wrong numbers of bits in the circuits, and see if you're getting similar phase errors?

**Comment by jakelishman** [comment] 2023-12-20 17:50
Terra 0.23 fixed the issues I was able to determine from this issue, so I'll close this now as fixed / can't reproduce, but please feel free to re-open it if I'm mistaken and there's still an issue here.

**Closed by jakelishman** 2023-12-20 17:50 UTC
Labels: bug
