### ISSUE TITLE
broken formatting in deprecation policy page

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11168] opened 2023-11-01 15:06 UTC
In https://qiskit.org/documentation/deprecation_policy.html, the code block seems broken:

![Screenshot 2023-11-01 at 16 04 45](https://github.com/Qiskit/qiskit/assets/766693/f1e70b36-38e6-4442-985a-336ce962fe42)

**Comment by shindodkar** [comment] 2023-11-01 18:12
would you like to give  some suggestion/hint on this issue

**Comment by jakelishman** [comment] 2023-11-02 12:30
The aim of the issue is to fix the file `docs/deprecation_policy.rst` so the pictured code block appears properly.  It looks likely to me that there might be a `::` at the end of the previous paragraph instead of a `:`, but I haven't looked in detail.

**Comment by AngeloDanducci** [comment] 2023-11-16 20:53
Closing as fixed per #11186

**Closed as completed by AngeloDanducci** 2023-11-16 20:53 UTC
Labels: good first issue, documentation
