### ISSUE TITLE
Measurements on different basis

### ISSUE THREAD

**Issue by aabennak** [Qiskit/qiskit#11443] opened 2023-12-20 16:56 UTC
### What should we add?

I'm suggesting that there would be methods added that would measure on the x and y basis rather than just the z basis.

They could be added as: measure_x(arg) and measure_y(arg).

It's a pretty easy task that I'd like to contribute to. My reference would be the implementation outlined in: https://arxiv.org/abs/1804.03719

**Comment by yaelbh** [comment] 2023-12-20 17:16
Thanks. Please be aware that it's less easy than it seems, because the transpiler may assume that all measurements are z-basis (and replacing e.g. x-basis measurements with z-basis measurements encapsulated by Hadamard gates brings its own complexities).

See previous attempts in #7716 and references therein to other issues and pull requests.

**Comment by jakelishman** [comment] 2023-12-20 17:45
Thanks for the interest in contributing!

I agree with the above - the idea of generalised measurements is something we're interested in, but actually implementing it safely has heavy implications all around the transpiler and the interpretation of circuits and the primitives in a way that I don't think we can fulfil right now.  At any rate, this issue is a duplicate of #3967, so I'd like to close this to keep discussion a little more localised - please feel free to comment on that issue, though the problems we have with generalisations will still hold, and right now, I'm not certain of a path forwards here.

**Comment by jakelishman** [comment] 2023-12-20 17:45
Duplicate of #3967

**Closed as not planned by jakelishman** 2023-12-20 17:45 UTC
Labels: type: feature request
