### ISSUE TITLE
Failure to visualize transpiled dynamic circuits

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit#10821] opened 2023-09-12 13:30 UTC
### Environment

- **Qiskit Terra version**: 0.25.1
- **Python version**: 
- **Operating system**: 

### What is happening?

Visualization of transpiled dynamic circuits fails.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile

ancilla = QuantumRegister(1, name="ancilla")
system = QuantumRegister(1, name = "system")
cr = ClassicalRegister(1)

qc = QuantumCircuit(ancilla, system, cr)
qc.measure(0, cr)

with qc.if_test((cr, 0)):  
    qc.h(system[0]) 
qc.draw()
```
is
<img width="322" alt="image" src="https://github.com/Qiskit/qiskit/assets/6814928/430af892-b8bb-48a2-b47e-ba181fd5a4f8">

However, if I transpile it, I got
```python
from qiskit_ibm_provider import IBMProvider

transpiled = transpile(qc, IBMProvider().get_backend("ibmq_manila"))
transpiled.draw()
```

<img width="526" alt="image" src="https://github.com/Qiskit/qiskit/assets/6814928/316ae9a9-f628-4456-895e-188cff66e0e3">

### What should happen?

One qubit gate should be in the if-else.

**Comment by mtreinish** [comment] 2023-09-12 13:41
This is a duplicate of: https://github.com/Qiskit/qiskit/issues/10601 so I'm going to close this as such. Feel free to reopen though if I'm missing something

**Closed as not planned by mtreinish** 2023-09-12 13:41 UTC
Labels: bug
