### ISSUE TITLE
queue_position and pending_jobs are not consistent

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit#503] opened 2018-05-24 11:25 UTC
It seems that the `queue_position` is always of the multiplicity of three. 

## Current Behavior

The pending jobs is 6, but the queue_position is 21... 
```
ibmqx5 : 16 qubits, 16 transmon 2x8 ladder {'available': True, 'pending_jobs': 6, 'backend': 'ibmqx5'}
```
But ...
```
{
  "backend": {
    "id": "...",
    "name": "ibmqx5"
  },
  "creationDate": "2018-05-24T11:03:31.358Z",
  "id": "...",
  "infoQueue": {
    "position": 21,
    "status": "PENDING_IN_QUEUE"
  },
  "maxCredits": 10,
  "qasms": [

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

**Comment by ajavadia** [comment] 2018-05-24 20:26
Hi @rraymondhp. `queue_position` and `pending_jobs` are not the same.

Pending jobs is the number of actual jobs pending to be executed on the backend. 

But queue_position is not as straightforward, as there are different queues based on user level and priority. So we calculate a worst-case position for your queue position. Being a multiple of 3 is apparently a product of this worst-case calculation. I'll double check.

**Comment by ajavadia** [comment] 2018-05-25 12:12
Ok I confirmed that the multiples of 3 are indeed due to reporting a conservative queue position, considering there are 3 queues. Your actual job position will be equal or smaller than this.
So I am closing this as not a bug.

**Closed as completed by ajavadia** 2018-05-25 12:12 UTC
